pipeline {
    agent any

    tools {
        git 'Default'
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', numToKeepStr: '10'))
        disableConcurrentBuilds()
    }

    environment {
        TELEGRAM_BOT_TOKEN = credentials('telegram-bot-token')
        ADMIN_API_KEY      = credentials('admin-api-key')
    }

    stages {
        stage('Build') {
            steps {
                sh './jenkins/02-build/build.sh'
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/02-build/test.sh'
            }
        }
    }

    post {
        success { archiveArtifacts artifacts: 'TripPlannerBot/build/libs/*.jar' }
    }
}
