apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripplanner
  template:
    metadata:
      labels:
        app: tripplanner
    spec:
      containers:
        - name: app
          image: __APP_IMAGE__
          imagePullPolicy: __IMAGE_PULL_POLICY__
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: tripplanner-secrets
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
