heat_template_version: 2015-10-15
description: TripPlanner Bot Node.  Resources are deleted when stack is deleted.

parameters:
  image:
    type: string
    description: Glance image name or ID (e.g. Ubuntu 22.04)
    default: ununtu-22.04
  flavor:
    type: string
    description: Nova flavor for instance
    default: m1.small
  key_name:
    type: string
    description: SSH key pair name for VM access
  network:
    type: string
    description: Network name or ID for the instance
resources:
  wait_handle:
    type: OS::Heat::WaitConditionHandle

  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      timeout: 1800  # wait up to 15 minutes

  app_secgroup:
    type: OS::Neutron::SecurityGroup
    deletion_policy: Delete
    properties:
      name: tripplanner-app-sg
      description: SSH and TripPlanner app ports
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
          remote_ip_prefix: 0.0.0.0/0
        - protocol: tcp
          port_range_min: 27017
          port_range_max: 27017
          remote_ip_prefix: 0.0.0.0/0

  server_port:
    type: OS::Neutron::Port
    deletion_policy: Delete
    properties:
      network: { get_param: network }
      security_groups:
        - { get_resource: app_secgroup }

  vm:
    type: OS::Nova::Server
    deletion_policy: Delete
    properties:
      name: michalec-tripplanner
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            bootcmd:
              - |
                curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc \
                  | gpg --dearmor > /usr/share/keyrings/mongodb-server-8.0.gpg
            apt:
              preserve_sources_list: false
              primary:
                - arches: [default]
                  uri: http://mirror.yandex.ru/ubuntu/
              security:
                - arches: [default]
                  uri: http://mirror.yandex.ru/ubuntu/
              sources:
                mongodb-org:
                  source: >
                    deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg]
                    https://repo.mongodb.org/apt/ubuntu $RELEASE/mongodb-org/8.0 multiverse
            package_update: true
            package_upgrade: true
            packages:
              - openjdk-21-jdk
              - mongodb-org
              - curl
            users:
              - name: tripplanner
                groups: []
              - name: ubuntu
                groups: [sudo]
                ssh_authorized_keys:
                  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJRy2xTx1XiYIsphsrJyZtQ3qguTFxwIfHOY+v7/j7yB michalec"
                  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4WVScOM5OSqrkr9f/CTKgjTQ3B9sSjdHRpFyhrWKYrjYlGnh8Mf64ClzIq+MFI6g5QcBYTsbvfv0Qd3rJmbV9x3n7fmJfx1HbAVRvCB3ELoQd0wMAaJpMSjobvBqSe/mMPysrf4TndFcp3j7nJ/c+9RpPL/QByLQUofukXbJ2QHZ3uZGYQ/6ujYsJwI6/32wCyIRahmciTO7lIgZzve3aYhZuCzCt0ObJIx4ZDfjZcv2genNfDNHkeUuDMj3RSkDQeAWzpb/Ya+gCepKpJzfsUASRcrGgeD4q+oPNG2vSaYvn0zLlbDdLCZYo67vKu9yZShh4XEZAObbyI9F6uA+Q4jVYm+n+BXkYz3C7THXe7RemJzQwg8CLj79KaTd5wQP9yeSXnQqJsncS+Y8rkG7yS8jJh78U/Gp8TfXqFZDMmWEiqm2nBkpEGc0IQvAGtVP47qxifONXYoZ7AgUgn63gCQ7UTbFlJQE9qqyk6mFHbcHW4tz0MRW2cqm84XAlCj8= jenkins@michalec"
            runcmd:
              - systemctl enable mongod
              - systemctl start mongod
              - |
                $WAIT_HANDLE_CURL_CLI \
                -d '{"status":"SUCCESS","reason":"cloud-init completed"}'
          params:
            $WAIT_HANDLE_CURL_CLI: { get_attr: [ wait_handle, curl_cli ] }

outputs:
  instance_id:
    description: Instance ID
    value: { get_resource: vm }
  instance_name:
    description: Instance name
    value: { get_attr: [ vm, name ] }
  instance_ip:
    description: IP of the instance
    value: { get_attr: [ server_port, fixed_ips, 0, ip_address ] }
