pipeline {
    agent {
        label 'michalec'
    }

    tools {
        git 'Default'
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', numToKeepStr: '10'))
        disableConcurrentBuilds()
    }

    parameters {
        string(name: 'STACK_NAME', defaultValue: 'michalec-tripplanner', description: 'Heat stack name')
        string(name: 'IMAGE',      defaultValue: 'ununtu-22.04',         description: 'Glance image')
        string(name: 'FLAVOR',     defaultValue: 'm1.small',             description: 'Nova flavor')
        string(name: 'KEY_NAME',   defaultValue: 'Martin Michalec',       description: 'SSH key pair name')
        string(name: 'NETWORK',    defaultValue: 'sutdents-net',         description: 'Network name or ID')

        string (name: 'OS_AUTH_URL',             defaultValue: 'https://cloud.crplab.ru:5000/v3', description: 'OpenStack authentication URL')
        string (name: 'OS_PROJECT_NAME',         defaultValue: 'students',                        description: 'OpenStack project name')
        string (name: 'OS_USERNAME',             defaultValue: 'ccstudent2026',                   description: 'OpenStack username')
        string (name: 'OS_USER_DOMAIN_NAME',     defaultValue: 'default',                         description: 'OpenStack user domain name')
        string (name: 'OS_PROJECT_DOMAIN_NAME',  defaultValue: 'default',                         description: 'OpenStack project domain name')
        string (name: 'OS_IDENTITY_API_VERSION', defaultValue: '3',                               description: 'OpenStack identity API version')
    }

    environment {
        OS_PASSWORD = credentials('os-password')
    }

    stages {
        stage('Deploy Heat Stack') {
            steps {
                sh './jenkins/orchestrate/deploy.sh'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'heat/*.yaml', allowEmptyArchive: true
        }
    }
}
