pipeline {
    agent any

    tools {
        git 'Default'
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '14', numToKeepStr: '10'))
        disableConcurrentBuilds()
    }

    parameters {
        string(name: 'VM_HOST', description: 'IP/hostname of VM')
        string(name: 'SSH_USER',  defaultValue: 'ubuntu', description: 'SSH user on VM (ubuntu for Ubuntu cloud images)')
        string(name: 'SSH_CREDENTIAL_ID', defaultValue: 'ya-cloud-ssh', description: 'Jenkins SSH credential')
        string(name: 'BUILD_JOB', defaultValue: '02-build',  description: 'Upstream build job that produces JAR (not deploy job!)')
    }

    environment {
        TELEGRAM_BOT_TOKEN = credentials('telegram-bot-token')
        ADMIN_API_KEY = credentials('admin-api-key')
    }

    stages {
        stage('Copy Artifact') {
            steps {
                copyArtifacts(
                    filter: 'TripPlannerBot/build/libs/*.jar',
                    projectName: "${params.BUILD_JOB}",
                    selector: specific('lastSuccessfulBuild')
                )
            }
        }

        stage('Deploy Systemd Service') {
            steps {
               withCredentials([
                    sshUserPrivateKey(credentialsId: params.SSH_CREDENTIAL_ID, keyFileVariable: 'SSH_KEY'),
                ]) {
                    sh './jenkins/04-deploy/deploy.sh'
                }
            }
        }
    }
}
